```{r primer_plot, fig.align='center', fig.cap="Gráfico uso de plot"}
x=c(2,6,4,9,-1)
y=c(1,8,4,-2,4)
plot(x,y)

```
si no se incorpora vector y, r interpreta x como si fuera y
```{r}
plot(2^(1:6))
```
para representar f(x)
```{r}
y= function(x){x^2+2*x+2}
plot(y)

```

```{r}
par(mfrow=c(1,2)) #2 graficos en linea
plot= plot(exp(1:20), xlab = "Indice",ylab = expression(e^{1:20}), main = "escala linear")

plotLog=plot(exp(1:20),log = "y",xlab ="Indice", ylab = expression(e^{1:20}),main = "Escala logaritmica en el eje y" )
```

#Parametros
```{r}
n=1:20
fib=(1/sqrt(5))*((1+sqrt(5))/2)^n - (1/sqrt(5))*((1-sqrt(5))/2)^n
plot(fib,xlab = "n",ylab = expression(F[n]), main = "Sucesión de Fibonacci", pch=21, col="powderblue")
```
```{r}
  x=(2*(1:20))
  y= (-1)^(1:20)*5*(1:20)
  plot(x,y,main = "Ejemplo", pch = 8, cex = 1, type = "b", lty = 4, lwd=4, xaxp=c(0,40,2),yaxp=c(-100,100,8))
```
##Añadir elementos a un grafico
```{r}
f<- function(x)  {x^2 -2*x +sqrt(abs(x))}

plot(f, xlim = c(-3,3))
points(0,0,pch=19)
points(-3:3,(-3:3)^2,col="blue")
abline(2,3,lty="dashed",col="red")
abline(v=2,lty="dotted",col="green")
abline(h=5,lty="dotdash",col="gray")
```

